import type { WatchlistItem } from '../types/watchlistItem.js';

/**
 * Realistic mock data for unit tests.
 * A small watchlist with movies and books in different statuses.
 */
export const mockWatchlist: WatchlistItem[] = [
  {
    id: '1',
    type: 'movie',
    title: 'Inception',
    genres: ['Sci-Fi', 'Action'],
    status: 'done',
    rating: 5,
    dateAdded: '2026-01-10',
    releaseYear: 2010,
    director: 'Christopher Nolan',
    coverUrl: 'https://image.tmdb.org/t/p/w200/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
  },
  {
    id: '2',
    type: 'movie',
    title: 'The Matrix',
    genres: ['Sci-Fi', 'Action'],
    status: 'watching',
    rating: null,
    dateAdded: '2026-02-15',
    releaseYear: 1999,
    coverUrl: 'https://www.themoviedb.org/t/p/w1280/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg',
  },
  {
    id: '3',
    type: 'book',
    title: 'Dune',
    genres: ['Sci-Fi', 'Adventure'],
    status: 'done',
    rating: 4,
    dateAdded: '2026-01-20',
    author: 'Frank Herbert',
    publishYear: 1965,
    coverUrl: 'https://covers.openlibrary.org/b/id/8904770-M.jpg',
  },
  {
    id: '4',
    type: 'book',
    title: '1984',
    genres: ['Dystopian', 'Fiction'],
    status: 'reading',
    rating: null,
    dateAdded: '2026-03-01',
    author: 'George Orwell',
    publishYear: 1949,
    coverUrl: 'https://covers.openlibrary.org/b/id/8739161-M.jpg',
  },
  {
    id: '5',
    type: 'movie',
    title: 'Interstellar',
    genres: ['Sci-Fi', 'Drama'],
    status: 'want',
    rating: null,
    dateAdded: '2026-04-05',
    releaseYear: 2014,
    director: 'Christopher Nolan',
    coverUrl: 'https://www.themoviedb.org/t/p/w1280/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  },
  {
    id: '6',
    type: 'book',
    title: 'The Hobbit',
    genres: ['Fantasy', 'Adventure'],
    status: 'want',
    rating: null,
    dateAdded: '2026-05-12',
    author: 'J.R.R. Tolkien',
    publishYear: 1937,
    coverUrl: 'https://covers.openlibrary.org/b/id/6979861-M.jpg',
  },
  {
    id: '7',
    type: 'movie',
    title: 'Blade Runner 2049',
    genres: ['Sci-Fi', 'Drama'],
    status: 'done',
    rating: 4,
    dateAdded: '2026-02-28',
    releaseYear: 2017,
    coverUrl: 'https://www.themoviedb.org/t/p/w1280/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
  },
  {
    id: '8',
    type: 'movie',
    title: 'Parasite',
    genres: ['Thriller', 'Drama'],
    status: 'done',
    rating: 3,
    dateAdded: '2026-03-20',
    releaseYear: 2019,
    director: 'Bong Joon-ho',
    coverUrl: 'https://www.themoviedb.org/t/p/w1280/4DGPORlVIDIQvsuSDnM4uXKMjWS.jpg',
  },
  {
    id: '9',
    type: 'book',
    title: 'Project Hail Mary',
    genres: ['Sci-Fi', 'Adventure'],
    status: 'want',
    rating: null,
    dateAdded: '2026-06-01',
    author: 'Andy Weir',
    publishYear: 2021,
    coverUrl: 'https://covers.openlibrary.org/b/id/12624743-M.jpg',
  },
  {
    id: '10',
    type: 'movie',
    title: 'Everything Everywhere All at Once',
    genres: ['Sci-Fi', 'Comedy'],
    status: 'watching',
    rating: null,
    dateAdded: '2026-06-20',
    releaseYear: 2022,
    director: 'Daniel Kwan, Daniel Scheinert',
    coverUrl: 'https://www.themoviedb.org/t/p/w1280/u68AjlvlutfEIcpmbYpKcdi09ut.jpg',
  }
];

export const emptyWatchlist: WatchlistItem[] = [];
